document.addEventListener("DOMContentLoaded", function() {
    const startButton = document.getElementById("start-button");
    const stopButton = document.getElementById("stop-button");
    const speechOutput = document.getElementById("speech-output");
    const questionContainer = document.getElementById("question-container");

    // Define your interview questions here
    const questions = [
        "Question: What is your purpose for travel? Answer, Answer, Answer: I intend to travel to the United States to pursue higher education at Winthrop University in Rock Hill, South Carolina. I have been admitted to the computer science / cybersecurity / computer and information science program and plan to commence studies in the upcoming fall term.",
        "Question: Why do you want to study in the U.S.? Answer, Answer, Answer 1: The U.S. offers a flexible education system, which I believe will help me excel in my future career. As a student in the U.S., I can select from a wide range of programs to explore various fields. I will get the opportunity to experiment with other courses to take a peek at what they consist of, which will help broaden my knowledge. Additionally, I prefer a balance between practical and theoretical teaching, but the Nigerian school system is more theory-oriented. In high school, I looked forward to hands-on labs, projects, and critical thinking activities, which are lacking in Nigeria’s theory-focused system. The U.S. education system provides this balance, making it the ideal environment for me to develop my career fully. OR: Answer, Answer, Answer 2: I have always wanted to attend Winthrop since high school. My sponsor’s daughter attended and gave excellent reviews. Despite its ups and downs, the overall experience is highly rewarding. Winthrop boasts an honored and experienced faculty, impressive rankings, and achievements, such as being one of the top 5 public schools in South Carolina. It’s a school worth attending and it happens to be located in a country that makes the schooling experience much better because the U.S. is an advanced country, providing access to cutting-edge technology and lab equipment. This exposure will be invaluable when I start working on bringing advanced innovations to Nigeria.",
        "Question: Why the U.S.A, why not another country?  Answer,  Answer, Answer: First of all, Winthrop University, which I have always wanted to attend, is located in the U.S. U.S. schools have vibrant campus life with numerous clubs and organizations that broaden students' knowledge and experiences. My education will benefit not just me and my family, but also those around me and Nigeria as a whole. By the time I complete my undergraduate studies and return to Nigeria, I will have gained valuable knowledge to get secure a high-paying job, start companies, help transform lives, and establish non-profit organizations. Studying in the U.S. will also give me an edge in the Nigerian job market, boosting my career prospects. I will be prioritized over applicants who studied locally due to my broader knowledge base. My elder siblings, who studied in Nigeria, faced difficulties before they could secure their current high-paying jobs and they have advised me to study abroad based on their experience. Additionally, the U.S. offers excellent support for international students. I experienced this support firsthand from Winthrop officials during my admission process. Despite being thousands of miles away, their prompt and helpful email communication made me feel as though I had known them for years, and Winthrop already feels like home.",
        "Question: Have you visited the U.S. before? Answer, Answer, Answer: No I haven’t. I have never had the chance to visit. This will be my first visit.",
        "Question: Have you booked your tickets? Answer, Answer, Answer: {Answer will depend on the situation at that time}",
        "Question: Do you have any friends, family, or relatives in the U.S.? Answer, Answer, Answer: I have a friend in Minnesota who is studying medicine.",
        "Question: What do you know about American culture? Answer, Answer, Answer: One of America's defining features is its emphasis on freedom of speech and human rights expression. Unlike Nigerian schools, American students are encouraged to voice their opinions, suggestions, and criticisms to their professors openly. Additionally, American culture is known for its love of sports and recreation, particularly American football and basketball, which has piqued my interest. What excites me most about studying in America is the culture of competition. Whether in schools, workplaces, organizations, or politics, competition is always prevalent. I look forward to competing with classmates in hackathons and other events, which will enhance the educational experience and make it more enjoyable.",
        "Question: Why should you be given a visa? Answer, Answer, Answer: Granting me this visa will provide a great opportunity to learn from top professors, acquire valuable knowledge, and have a wonderful college experience as I will be attending my dream college. This, in turn, will help in the development of my great country, Nigeria. I pledge to be on my best behavior while studying in the U.S. and to not break any laws, rules, and regulations. I will stay in school and complete my studies before returning to work in the Nigerian FINTECH industry as an ethical hacker. I believe the U.S. offers high-quality education and excellent academic opportunities in my chosen field of study. Its education system utilizes advanced methods and technology to bring out the best in students who are committed to their success and I am determined to excel in my chosen career and contribute significantly to the Nigerian FINTECH industry.",
        "Question: What will you do if your visa is rejected? Answer, Answer, Answer 1: It has long been my wish to study at Winthrop University, but I will respect the embassy's decision. If needed, I will ensure to prepare all necessary documents and information for my next application to make the most of a second chance. Education in the U.S. is excellent, but time is more precious than any other commodity. If my second application is also rejected, I won't waste time trying again. Instead, I will pursue my backup plans for my life. OR: Answer 2: I will consider it a blessing in disguise. I will re-analyze my application, identify where I went wrong, and try again. Education in the U.S. is excellent, but time is more precious than any other commodity. If my second application is also rejected, I won't waste time trying again. Instead, I will pursue my backup plans for my life. OR: Answer 3: Rejecting my visa will undoubtedly have a significant impact on my life, as it will change my life’s trajectory. My supporters, friends, and professors at Winthrop University who have eagerly anticipated my arrival will also be disappointed. Education in the U.S. is excellent, but time is more precious than any other commodity. If my second application is also rejected, I won't waste time trying again. Instead, I will pursue my backup plans for my life.",
        "Question: What are your backup plans? Answer, Answer, Answer: If my visa is rejected, I will apply to a Nigerian university to study computer science / cybersecurity / computer and information science while also enrolling in a technical school for practical training in solar and renewable energy. Solar energy is still emerging in Nigeria and Africa, and being a computer science / cybersecurity / computer and information science graduate, combined with skills in solar and renewable energy, will make me unstoppable. I will have an excellent career, and my competition will be intimidated. When they hear the name "Wisdom Ona," they will shudder (smiles).",
        "Question: Why did you select this university? Answer, Answer, Answer: I selected Winthrop for several reasons but I’d like to start with; Winthrop’s reputation and academic excellence: its reputation and academic excellence. It is a highly respected institution with strong academic programs. Winthrop has a long history of academic excellence, and many of its graduates become top executives in their fields. Winthrop’s friendly and welcoming nature: its friendly and welcoming demeanor which I experienced firsthand from the beginning of my application process until now. I have experienced exceptional support. The officials always responded to my emails and calls promptly. I was really moved that they cared so much and I wasn’t just a number compared to other schools that didn’t care much. For example, it took Central Piedmont Community College up to 3 days to respond to an email, and that is if they ever responded. Winthrop was the only school that cared whether or not I attended as they were always checking up on me to ask about the progress of my visa application. Winthrop’s experienced and highly respected faculty: Winthrop's faculty is highly respected in South Carolina. Many faculty members have won awards, conducted extensive research, and published multiple papers in their fields. Many of Winthrop’s faculty members are often invited as guest speakers at surrounding universities. Additionally, I have read online reviews from students and most of Winthrop’s faculty are highly recommended by students who say they would definitely take a class under the professors again if they had the chance to. Winthrop’s undergraduate research program: its amazing undergraduate research program. I do not have to wait until graduate school to partake in amazing research programs. {additional info here could also depend on the outcome of my emails to the professors in the undergraduate research program e.g. I have contacted X professor who agreed that I can partake in X research program} Winthrop’s recommendations and proximity: the fact that it was highly recommended by my sponsor, Mr Salami, who lives close to the university. Although there are other schools in the area with lower admission criteria, Winthrop stood out for its academic prowess and overall college experience. Winthrop’s rankings: the fact that it is recognized by the South Carolina Commission on Higher Education as one of the top-rated universities in the state. It is also one of the top 10 public universities in South Carolina and has always been recognized as a university that has consistently exceeded standards since 2003. These factors combined make Winthrop the ideal choice for my higher education.",
        "Question: Mention the names of your professors at Winthrop. Note: I should message my professors to express my interest in a particular topic or project before arriving on campus. This could be useful to mention in my interview if relevant questions relating to this arise. Information: My professors are: (answers may change when I start registering for classes). Doctor Estelle Newton - BIOL 150 (004 202480). Elements of living systems (3). Doctor Michael Whitney (Ph.D., Computing and Information Systems, UNC Charlotte |  Ph.D., Educational Administration, SIUC | Director of Digital Information Design (DIFD Degree Program) - CSCI 151 (003 202480). Overview of computer science (3:2:2). Kristen Abernathy - MATH 201. Mr. Tray Graham - ACAD 101 (072 202480) (Academic Strategies is a freshman course designed to teach first-year students academic strategies needed to be successful in college). Principles of the learning academy (1). Doctor Joanna Jackson (Ph.D, MSN, RN) - HCMT 200 (001 202480). Introduction to health care management (3). Doctor Eddie Lee - HIST 211 (001 202480). United States history to 1877 (3). Answer: For my freshman year, I’ll have about six (6) professors, professors {names}..., but I’m most eager to study under professors {names}………………… (based on the outcome of my emails to them).",
        "Question: In what city is Winthrop University located? Answer, Answer, Answer: Winthrop University is located in Rock Hill, South Carolina. Rock Hill, situated in York County, is the fifth most populous city in South Carolina with a population of over 70,000 people. The city was founded in 1852 and incorporated on February 26, 1870. It was named 'Rock Hill' due to the rocky hill encountered by railway builders at the time. Additional Information: Mayor - John Gettys. Area - 43.85 sq mi (113.58 km2). Population - 74372 (2020 census). Population estimate (2022) - 75,349. Elevation - 676 ft. Area codes - 803, 839. Zip codes - 29730, 29731, 29732, 29733, 29734. South Carolina capital - Columbia. Rock Hill to Columbia - 70 miles (110km) Rock Hill to Charlotte, North Carolina - 25 miles (40km)",
        "Question: In what state is Winthrop University located? Answer, Answer, Answer: Winthrop University is located in South Carolina, U.S.A. South Carolina is the 40th largest and 23rd most populous state in the U.S., with a population of over 5 million people. Its capital is Columbia, which has a population of over 130,000 people. The state has 46 counties and had a GDP of $259.93 billion in 2023. The most populous city is Charleston, with over 150,000 residents. Additional Information: Governor - Since 2017 - Henry Dargan McMaster (born May 27, 1947). Nickname - the Palmetto State. Motto - While I breathe, I hope. Largest County - Greenville. Area - 32,020 sq mi (82,932.7km2). Elevation - 350ft (110m). Population - 5,118,425 (2020). Population rank - 23rd state in the U.S. The Province of Carolina was formed in 1712 by the King of England - Charles I. The Constitution of South Carolina was adopted on March 26, 1776",
        "Question: What is your sponsor’s income (monthly and annual)? A Answer, Answer, nswer:",
        "Question: Do you have a statement from the sponsor on a bank letterhead? Answer, Answer, Answer",
        "Question: Do you have a financial affidavit from the U.S.-based sponsor? Answer, Answer, Answer: ",
        "Question: Do you have an invitation letter or affidavit from the U.S.-based sponsor offering you accommodation in his home and to handle your unsettled expenses? Answer, Answer, Answer",
        "Who is sponsoring your trip/studies? Answer, Answer, Answer:  A sponsor of mine - Mr Salami. He has also invited me to stay at his house during my studies. Here is an invitation letter from Mr. Salami (if asked) addressed to the consulate. He is a {occupation}, lives with his {household, noting that he has fewer people to support}, and earns {income}. I have his official bank statements with me if you'd like to see them (if asked).",
        "Question: How will your expenses be covered? Answer, Answer, Answer: I received a merit scholarship worth $16,000 from Winthrop University, awarded based on my SAT score and high school GPA. Additionally, I was also granted an international ambassador scholarship worth $14,500, with $14,000 being a tuition waiver already covered by my first scholarship, leaving $500 to be applied annually. The total scholarship value is $17,000 while the remaining estimated annual cost is approximately $28,000, with school fees at $12,000 and other expenses at $66,000, most of which are covered by scholarships. The remaining expenses like feeding and my basic needs will be covered by my sponsor, Mr. Salami.",
        "Question: Where will you be staying? Answer, Answer, Answer: I will reside at my sponsor, Mr. Salami’s residence, located at 430 Tysons Forest Drive, Rock Hill, South Carolina, which is approximately a five-minute drive from Winthrop University. I obtained approval from Winthrop to reside off-campus at Mr. Salami’s house after completing the housing exemption form, which was duly notarized by a certified official in the U.S.",
        "Question: Do you have a scholarship? Answer, Answer, Answer: Yes, I do. I received a merit scholarship worth $16,000 from Winthrop University, awarded based on my SAT score and high school GPA. I also received an international ambassador scholarship worth $14,500, but only $500 of that will be applied each year since the scholarship includes an out-of-state tuition waiver already covered by my first scholarship.",
        "What do you know about American culture?",
        "Why should you be given a visa?",
        "What will you do if your visa is rejected?",
        "In what city is Winthrop university located?",
        "Mention the names of your professors at winthrop university",
        "Will you come back home during vacations or holidays?",
        "How do you intend to manage health care and other expenses you will incur?",
        "What is your sponsor’s monthly income?",
        "What is your sponsor’s annual income?",
        "What is your university’s yearly expenses?",
        "Do you have a statement from the sponsor on a bank letterhead?",
        "Do you have a financial affidavit from the US-based sponsor?",
        
        // Add more questions as needed
    ];
    let synth = window.speechSynthesis;
    let isInterviewRunning = false;
    let interviewInterval;

    function speak(text) {
        // Create a new speech synthesis utterance
        let utterance = new SpeechSynthesisUtterance(text);
        // Speak the text
        synth.speak(utterance);
    }

    function displayQuestion() {
        // Select a random question
        const randomIndex = Math.floor(Math.random() * questions.length);
        const question = questions[randomIndex];
        speechOutput.textContent = question;
        speak(question);
    }

    function startInterview() {
        isInterviewRunning = true;
        startButton.style.display = "none";
        stopButton.style.display = "inline-block";
        interviewInterval = setInterval(displayQuestion, 15000); // Display a question every 20 seconds
        displayQuestion(); // Display the first question immediately
    }

    function stopInterview() {
        isInterviewRunning = false;
        clearInterval(interviewInterval);
        stopButton.style.display = "none";
        startButton.style.display = "inline-block";
    }

    startButton.addEventListener("click", startInterview);
    stopButton.addEventListener("click", stopInterview);
});
